//
// Activity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Activity: Codable, JSONEncodable, Hashable {

    public var actorName: String?
    public var description: String?
    public var actorProfileUrl: String?
    public var dateTimeUtc: Date?

    public init(actorName: String? = nil, description: String? = nil, actorProfileUrl: String? = nil, dateTimeUtc: Date? = nil) {
        self.actorName = actorName
        self.description = description
        self.actorProfileUrl = actorProfileUrl
        self.dateTimeUtc = dateTimeUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actorName
        case description
        case actorProfileUrl
        case dateTimeUtc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actorName, forKey: .actorName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(actorProfileUrl, forKey: .actorProfileUrl)
        try container.encodeIfPresent(dateTimeUtc, forKey: .dateTimeUtc)
    }
}

