//
// AllergyIntoleranceReaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AllergyIntoleranceReaction: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var manifestation: [CodeableConcept]

    public init(description: String? = nil, manifestation: [CodeableConcept]) {
        self.description = description
        self.manifestation = manifestation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case manifestation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(manifestation, forKey: .manifestation)
    }
}

