//
// ApiErrorType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ApiErrorType: String, Codable, CaseIterable {
    case unauthorized = "Unauthorized"
    case tooManyRequests = "TooManyRequests"
    case badRequest = "BadRequest"
    case notFound = "NotFound"
    case internalServerError = "InternalServerError"
    case dataConsentRequestExists = "DataConsentRequestExists"
}
