//
// CodeableConcept.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CodeableConcept: Codable, JSONEncodable, Hashable {

    public var coding: [Coding]?
    public var id: String?
    public var text: String?

    public init(coding: [Coding]? = nil, id: String? = nil, text: String? = nil) {
        self.coding = coding
        self.id = id
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case coding
        case id
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(coding, forKey: .coding)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(text, forKey: .text)
    }
}

