//
// Coding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Coding: Codable, JSONEncodable, Hashable {

    public var code: String?
    public var display: String?
    public var id: String?
    public var system: String?

    public init(code: String? = nil, display: String? = nil, id: String? = nil, system: String? = nil) {
        self.code = code
        self.display = display
        self.id = id
        self.system = system
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case display
        case id
        case system
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(display, forKey: .display)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(system, forKey: .system)
    }
}

