//
// CollectibleTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CollectibleTypes: String, Codable, CaseIterable {
    case identity = "Identity"
    case documents = "Documents"
    case financials = "Financials"
    case health = "Health"
}
