//
// ConsentedIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ConsentedIdentifier : Consented identifier details. */
public struct ConsentedIdentifier: Codable, JSONEncodable, Hashable {

    /** Identifier name. */
    public var name: String
    /** Identifier key. */
    public var key: String
    /** Identifier value type. */
    public var valueType: String
    /** Identifier value. */
    public var value: String

    public init(name: String, key: String, valueType: String, value: String) {
        self.name = name
        self.key = key
        self.valueType = valueType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case key
        case valueType
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(key, forKey: .key)
        try container.encode(valueType, forKey: .valueType)
        try container.encode(value, forKey: .value)
    }
}

