//
// CreateDataProcessingAgreement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** CreateDataProcessingAgreement : Create data processing agreement details. */
public struct CreateDataProcessingAgreement: Codable, JSONEncodable, Hashable {

    /** Agreement version. Agreement body content. */
    public var name: String
    public var issuerType: IssuerType
    /** Agreement attachment file URL. */
    public var agreementUrl: String

    public init(name: String, issuerType: IssuerType, agreementUrl: String) {
        self.name = name
        self.issuerType = issuerType
        self.agreementUrl = agreementUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case issuerType
        case agreementUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(issuerType, forKey: .issuerType)
        try container.encode(agreementUrl, forKey: .agreementUrl)
    }
}

