//
// CreateDataConsentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create individual data consent request */
public struct CreateDataConsentRequest: Codable, JSONEncodable, Hashable {

    /** Consent template id */
    public var consentTemplateId: UUID
    public var receiver: ConsentRequestReceiver

    public init(consentTemplateId: UUID, receiver: ConsentRequestReceiver) {
        self.consentTemplateId = consentTemplateId
        self.receiver = receiver
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case consentTemplateId
        case receiver
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(consentTemplateId, forKey: .consentTemplateId)
        try container.encode(receiver, forKey: .receiver)
    }
}

