//
// CreditCardHolders.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreditCardHolders: Codable, JSONEncodable, Hashable {

    public var holder: CreditCardHolder

    public init(holder: CreditCardHolder) {
        self.holder = holder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case holder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(holder, forKey: .holder)
    }
}

