//
// DataProtectionOfficer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataProtectionOfficer: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var email: String?
    public var phoneNumber: String?
    public var website: String?

    public init(name: String? = nil, email: String? = nil, phoneNumber: String? = nil, website: String? = nil) {
        self.name = name
        self.email = email
        self.phoneNumber = phoneNumber
        self.website = website
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case email
        case phoneNumber
        case website
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(website, forKey: .website)
    }
}

