//
// DataConsentFinancialsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataConsentFinancialsDto: Codable, Hashable {

    public var id: UUID?
    public var financials: [Financial]?
    public var approvedFinancials: [DataConsentRequestedFinancialAccount]?

    public init(id: UUID? = nil, financials: [Financial]? = nil, approvedFinancials: [DataConsentRequestedFinancialAccount]? = nil) {
        self.id = id
        self.financials = financials
        self.approvedFinancials = approvedFinancials
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case financials
        case approvedFinancials
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(financials, forKey: .financials)
        try container.encodeIfPresent(approvedFinancials, forKey: .approvedFinancials)
    }
}

