//
// DataConsentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataConsentRequest: Codable, Hashable {

    public var id: UUID?
    public var templateId: UUID?
    public var requestedAtUtc: Date?
    public var requestExpiredAtUtc: Date?
    public var transactionId: String?

    public init(id: UUID? = nil, templateId: UUID? = nil, requestedAtUtc: Date? = nil, requestExpiredAtUtc: Date? = nil, transactionId: String? = nil) {
        self.id = id
        self.templateId = templateId
        self.requestedAtUtc = requestedAtUtc
        self.requestExpiredAtUtc = requestExpiredAtUtc
        self.transactionId = transactionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case templateId
        case requestedAtUtc
        case requestExpiredAtUtc
        case transactionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(templateId, forKey: .templateId)
        try container.encodeIfPresent(requestedAtUtc, forKey: .requestedAtUtc)
        try container.encodeIfPresent(requestExpiredAtUtc, forKey: .requestExpiredAtUtc)
        try container.encodeIfPresent(transactionId, forKey: .transactionId)
    }
}

