//
// DataConsentDocumentIssuer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Data Consent document issuer details. */
public struct DataConsentDocumentIssuer: Codable, JSONEncodable, Hashable {

    /** Document issuer id. */
    public var id: UUID
    /** Document issuer name. */
    public var name: String

    public init(id: UUID, name: String) {
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}

