//
// Document.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Document: Codable, JSONEncodable, Hashable {

    public var fieldTitle: String
    public var fieldSlug: String
    public var drn: [String]
    public var requirement: DocumentsRequired

    public init(fieldTitle: String, fieldSlug: String, drn: [String], requirement: DocumentsRequired) {
        self.fieldTitle = fieldTitle
        self.fieldSlug = fieldSlug
        self.drn = drn
        self.requirement = requirement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fieldTitle = "field_title"
        case fieldSlug = "field_slug"
        case drn
        case requirement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fieldTitle, forKey: .fieldTitle)
        try container.encode(fieldSlug, forKey: .fieldSlug)
        try container.encode(drn, forKey: .drn)
        try container.encode(requirement, forKey: .requirement)
    }
}

