//
// DocumentCategoryType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DocumentCategoryType: String, Codable, CaseIterable {
    case health = "Health"
    case finance = "Finance"
    case education = "Education"
    case bills = "Bills"
    case tax = "Tax"
    case certificates = "Certificates"
    case invoices = "Invoices"
}
