//
// DocumentIssueRequestDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Document issue request details. */
public struct DocumentIssueRequestDetails: Codable, JSONEncodable, Hashable {

    /** Request Id. */
    public var id: UUID
    public var documentTypeId: UUID
    public var typeName: String
    public var identifier: String
    public var status: DocumentIssueRequestStatus
    public var description: String
    public var receiver: AnyCodable?
    public var issuedAtUtc: Date
    public var validFromUtc: Date
    public var expiresAtUtc: Date?
    public var metaData: AnyCodable?
    public var createdAtUtc: Date

    public init(id: UUID, documentTypeId: UUID, typeName: String, identifier: String, status: DocumentIssueRequestStatus, description: String, receiver: AnyCodable?, issuedAtUtc: Date, validFromUtc: Date, expiresAtUtc: Date? = nil, metaData: AnyCodable? = nil, createdAtUtc: Date) {
        self.id = id
        self.documentTypeId = documentTypeId
        self.typeName = typeName
        self.identifier = identifier
        self.status = status
        self.description = description
        self.receiver = receiver
        self.issuedAtUtc = issuedAtUtc
        self.validFromUtc = validFromUtc
        self.expiresAtUtc = expiresAtUtc
        self.metaData = metaData
        self.createdAtUtc = createdAtUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case documentTypeId
        case typeName
        case identifier
        case status
        case description
        case receiver
        case issuedAtUtc
        case validFromUtc
        case expiresAtUtc
        case metaData
        case createdAtUtc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(documentTypeId, forKey: .documentTypeId)
        try container.encode(typeName, forKey: .typeName)
        try container.encode(identifier, forKey: .identifier)
        try container.encode(status, forKey: .status)
        try container.encode(description, forKey: .description)
        try container.encode(receiver, forKey: .receiver)
        try container.encode(issuedAtUtc, forKey: .issuedAtUtc)
        try container.encode(validFromUtc, forKey: .validFromUtc)
        try container.encodeIfPresent(expiresAtUtc, forKey: .expiresAtUtc)
        try container.encodeIfPresent(metaData, forKey: .metaData)
        try container.encode(createdAtUtc, forKey: .createdAtUtc)
    }
}

