//
// EquityHoldingMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EquityHoldingMode: String, Codable, CaseIterable {
    case demat = "Demat"
    case physical = "Physical"
}
