//
// Equity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Equity: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var issuerName: String
    public var exchange: String
    public var isin: String
    public var units: Int64
    public var investmentValue: Double
    public var currentValue: Double
    public var currencyCode: String
    public var holder: Holder
    public var transactions: Bool

    public init(id: String, name: String, issuerName: String, exchange: String, isin: String, units: Int64, investmentValue: Double, currentValue: Double, currencyCode: String, holder: Holder, transactions: Bool) {
        self.id = id
        self.name = name
        self.issuerName = issuerName
        self.exchange = exchange
        self.isin = isin
        self.units = units
        self.investmentValue = investmentValue
        self.currentValue = currentValue
        self.currencyCode = currencyCode
        self.holder = holder
        self.transactions = transactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case issuerName = "issuer_name"
        case exchange
        case isin
        case units
        case investmentValue = "investment_value"
        case currentValue = "current_value"
        case currencyCode = "currency_code"
        case holder
        case transactions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(issuerName, forKey: .issuerName)
        try container.encode(exchange, forKey: .exchange)
        try container.encode(isin, forKey: .isin)
        try container.encode(units, forKey: .units)
        try container.encode(investmentValue, forKey: .investmentValue)
        try container.encode(currentValue, forKey: .currentValue)
        try container.encode(currencyCode, forKey: .currencyCode)
        try container.encode(holder, forKey: .holder)
        try container.encode(transactions, forKey: .transactions)
    }
}

