//
// EquityHoldings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EquityHoldings: Codable, JSONEncodable, Hashable {

    public var holding: EquityHolding
    public var type: EquityHoldingMode

    public init(holding: EquityHolding, type: EquityHoldingMode) {
        self.holding = holding
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case holding
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(holding, forKey: .holding)
        try container.encode(type, forKey: .type)
    }
}

