//
// EquitySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EquitySummary: Codable, JSONEncodable, Hashable {

    public var investment: EquityInvestment
    public var investmentValue: Double
    public var currentValue: Double

    public init(investment: EquityInvestment, investmentValue: Double, currentValue: Double) {
        self.investment = investment
        self.investmentValue = investmentValue
        self.currentValue = currentValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case investment
        case investmentValue
        case currentValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(investment, forKey: .investment)
        try container.encode(investmentValue, forKey: .investmentValue)
        try container.encode(currentValue, forKey: .currentValue)
    }
}

