//
// ErrorType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ErrorType: String, Codable, CaseIterable {
    case invalidAccessToken = "InvalidAccessToken"
    case invalidRefreshToken = "InvalidRefreshToken"
    case insufficientPermission = "InsufficientPermission"
    case internalServerError = "InternalServerError"
    case badRequest = "BadRequest"
    case notFound = "NotFound"
    case invalidOrganization = "InvalidOrganization"
    case invalidFileUploadType = "InvalidFileUploadType"
}
