//
// Financial.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Financial: Codable, Hashable {

    public var accountField: String?
    public var customKey: String?
    public var accounts: [FinancialAccounts]?
    public var requirement: DocumentsRequired?

    public init(accountField: String? = nil, customKey: String? = nil, accounts: [FinancialAccounts]? = nil, requirement: DocumentsRequired? = nil) {
        self.accountField = accountField
        self.customKey = customKey
        self.accounts = accounts
        self.requirement = requirement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountField
        case customKey
        case accounts
        case requirement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountField, forKey: .accountField)
        try container.encodeIfPresent(customKey, forKey: .customKey)
        try container.encodeIfPresent(accounts, forKey: .accounts)
        try container.encodeIfPresent(requirement, forKey: .requirement)
    }
}

