//
// FinancialAccounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FinancialAccounts: Codable, Hashable {

    public var drn: String?
    public var financialAccountDetailsRequired: [FinancialAccountDetailsRequired]?
    public var startDate: Date?
    public var endDate: Date?

    public init(drn: String? = nil, financialAccountDetailsRequired: [FinancialAccountDetailsRequired]? = nil, startDate: Date? = nil, endDate: Date? = nil) {
        self.drn = drn
        self.financialAccountDetailsRequired = financialAccountDetailsRequired
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case drn
        case financialAccountDetailsRequired
        case startDate
        case endDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(drn, forKey: .drn)
        try container.encodeIfPresent(financialAccountDetailsRequired, forKey: .financialAccountDetailsRequired)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
    }
}

