//
// FinancialAccounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FinancialAccounts: Codable, JSONEncodable, Hashable {

    public var drn: String?
    public var requiredDetails: [FinancialAccountDetailsRequired]?
    public var startDate: Date?
    public var endDate: Date?

    public init(drn: String? = nil, requiredDetails: [FinancialAccountDetailsRequired]? = nil, startDate: Date? = nil, endDate: Date? = nil) {
        self.drn = drn
        self.requiredDetails = requiredDetails
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case drn
        case requiredDetails = "required_details"
        case startDate = "start_date"
        case endDate = "end_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(drn, forKey: .drn)
        try container.encodeIfPresent(requiredDetails, forKey: .requiredDetails)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
    }
}

