//
// FinancialAccountCategoryType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FinancialAccountCategoryType: String, Codable, CaseIterable {
    case savings = "Savings"
    case insurance = "Insurance"
    case loan = "Loan"
    case creditCard = "CreditCard"
    case bill = "Bill"
    case investment = "Investment"
    case reward = "Reward"
}
