//
// Holders.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Holders: Codable, JSONEncodable, Hashable {

    public var holder: Holder
    public var type: HoldersType

    public init(holder: Holder, type: HoldersType) {
        self.holder = holder
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case holder
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(holder, forKey: .holder)
        try container.encode(type, forKey: .type)
    }
}

