//
// Holder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Holder: Codable, JSONEncodable, Hashable {

    public var name: String
    public var dateOfBirth: Date?
    public var mobile: String?
    public var dematId: String
    public var email: String
    public var pan: String?

    public init(name: String, dateOfBirth: Date? = nil, mobile: String? = nil, dematId: String, email: String, pan: String? = nil) {
        self.name = name
        self.dateOfBirth = dateOfBirth
        self.mobile = mobile
        self.dematId = dematId
        self.email = email
        self.pan = pan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case dateOfBirth = "date_of_birth"
        case mobile
        case dematId = "demat_id"
        case email
        case pan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth)
        try container.encodeIfPresent(mobile, forKey: .mobile)
        try container.encode(dematId, forKey: .dematId)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(pan, forKey: .pan)
    }
}

