//
// IdentitySupportedFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IdentitySupportedFields: Codable, Hashable {

    public var iconCodePoint: Int
    public var title: String
    public var description: String?
    public var key: String
    public var dataType: String

    public init(iconCodePoint: Int, title: String, description: String? = nil, key: String, dataType: String) {
        self.iconCodePoint = iconCodePoint
        self.title = title
        self.description = description
        self.key = key
        self.dataType = dataType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iconCodePoint
        case title
        case description
        case key
        case dataType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(iconCodePoint, forKey: .iconCodePoint)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(key, forKey: .key)
        try container.encode(dataType, forKey: .dataType)
    }
}

