//
// IdentityField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** IdentityField : Identity field of Consent request template. */
public struct IdentityField: Codable, JSONEncodable, Hashable {

    /** Field title. */
    public var title: String
    /** Field description. */
    public var description: String?
    /** Field key. */
    public var key: String
    /** Field data type. */
    public var dataType: String

    public init(title: String, description: String? = nil, key: String, dataType: String) {
        self.title = title
        self.description = description
        self.key = key
        self.dataType = dataType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case key
        case dataType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(key, forKey: .key)
        try container.encode(dataType, forKey: .dataType)
    }
}

