//
// IndividualDataConsentDocument.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Individual data consent document details. */
public struct IndividualDataConsentDocument: Codable, JSONEncodable, Hashable {

    /** Name of consent approver individual. */
    public var approver: String
    /** Document id. */
    public var id: UUID
    /** Data consent id. */
    public var consentId: UUID
    /** Document name. */
    public var name: String
    /** Document identifier. */
    public var identifier: String

    public init(approver: String, id: UUID, consentId: UUID, name: String, identifier: String) {
        self.approver = approver
        self.id = id
        self.consentId = consentId
        self.name = name
        self.identifier = identifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case approver
        case id
        case consentId
        case name
        case identifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(approver, forKey: .approver)
        try container.encode(id, forKey: .id)
        try container.encode(consentId, forKey: .consentId)
        try container.encode(name, forKey: .name)
        try container.encode(identifier, forKey: .identifier)
    }
}

