//
// IssuedDocument.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IssuedDocument: Codable, JSONEncodable, Hashable {

    public var documentId: UUID?
    public var identifier: String?
    public var documentType: String?
    public var issuedTo: String?
    public var issuedAtUtc: Date?

    public init(documentId: UUID? = nil, identifier: String? = nil, documentType: String? = nil, issuedTo: String? = nil, issuedAtUtc: Date? = nil) {
        self.documentId = documentId
        self.identifier = identifier
        self.documentType = documentType
        self.issuedTo = issuedTo
        self.issuedAtUtc = issuedAtUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentId
        case identifier
        case documentType
        case issuedTo
        case issuedAtUtc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(documentId, forKey: .documentId)
        try container.encodeIfPresent(identifier, forKey: .identifier)
        try container.encodeIfPresent(documentType, forKey: .documentType)
        try container.encodeIfPresent(issuedTo, forKey: .issuedTo)
        try container.encodeIfPresent(issuedAtUtc, forKey: .issuedAtUtc)
    }
}

