//
// IssuedDocumentPaginatedListItemsOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IssuedDocumentPaginatedListItemsOneOf: Codable, JSONEncodable {
    case typeIssuedDocument(IssuedDocument)
    case typeIssuedDocumentDetails(IssuedDocumentDetails)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeIssuedDocument(let value):
            try container.encode(value)
        case .typeIssuedDocumentDetails(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(IssuedDocument.self) {
            self = .typeIssuedDocument(value)
        } else if let value = try? container.decode(IssuedDocumentDetails.self) {
            self = .typeIssuedDocumentDetails(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of IssuedDocumentPaginatedListItemsOneOf"))
        }
    }
}

