//
// IssuedDocument.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Issued Document Identifier. */
public struct IssuedDocument: Codable, JSONEncodable, Hashable {

    /** Document Id. */
    public var id: UUID
    /** Document Identifier. */
    public var identifier: String
    /** Document type name. */
    public var documentType: String
    /** User name. */
    public var issuedTo: String
    /** Issued datetime in UTC timezone. */
    public var issuedAtUtc: Date

    public init(id: UUID, identifier: String, documentType: String, issuedTo: String, issuedAtUtc: Date) {
        self.id = id
        self.identifier = identifier
        self.documentType = documentType
        self.issuedTo = issuedTo
        self.issuedAtUtc = issuedAtUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case identifier
        case documentType
        case issuedTo
        case issuedAtUtc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(identifier, forKey: .identifier)
        try container.encode(documentType, forKey: .documentType)
        try container.encode(issuedTo, forKey: .issuedTo)
        try container.encode(issuedAtUtc, forKey: .issuedAtUtc)
    }
}

