//
// MedicalRecordField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** MedicalRecordField : Medical record field of consent request template. */
public struct MedicalRecordField: Codable, JSONEncodable, Hashable {

    /** Field title. */
    public var fieldTitle: String
    /** Field slug. */
    public var fieldSlug: String
    /** Field DRNs. */
    public var drns: [String]

    public init(fieldTitle: String, fieldSlug: String, drns: [String]) {
        self.fieldTitle = fieldTitle
        self.fieldSlug = fieldSlug
        self.drns = drns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fieldTitle
        case fieldSlug
        case drns
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fieldTitle, forKey: .fieldTitle)
        try container.encode(fieldSlug, forKey: .fieldSlug)
        try container.encode(drns, forKey: .drns)
    }
}

