//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelError: Codable, JSONEncodable, Hashable {

    public var title: String
    public var status: Int
    public var errorType: ApiErrorType

    public init(title: String, status: Int, errorType: ApiErrorType) {
        self.title = title
        self.status = status
        self.errorType = errorType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case status
        case errorType = "error_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(status, forKey: .status)
        try container.encode(errorType, forKey: .errorType)
    }
}

