//
// MutualFundInvestment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MutualFundInvestment: Codable, JSONEncodable, Hashable {

    public var holdings: MutualFundHoldings

    public init(holdings: MutualFundHoldings) {
        self.holdings = holdings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case holdings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(holdings, forKey: .holdings)
    }
}

