//
// MutualFundFundType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MutualFundFundType: String, Codable, CaseIterable {
    case equity = "Equity"
    case debt = "Debt"
    case hybrid = "Hybrid"
    case solutionOrientedSchemes = "SolutionOrientedSchemes"
    case others = "Others"
}
