//
// MutualFundSchemePlan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MutualFundSchemePlan: String, Codable, CaseIterable {
    case direct = "Direct"
    case regular = "Regular"
}
