//
// MutualFundSchemeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MutualFundSchemeType: String, Codable, CaseIterable {
    case equitySchemes = "EquitySchemes"
    case debtSchemes = "DebtSchemes"
    case hybridSchemes = "HybridSchemes"
    case solutionOrientedSchemes = "SolutionOrientedSchemes"
    case otherSchemes = "OtherSchemes"
}
