//
// PaymentOrderItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentOrderItem: Codable, JSONEncodable, Hashable {

    public var name: String
    public var amount: Double

    public init(name: String, amount: Double) {
        self.name = name
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(amount, forKey: .amount)
    }
}

