//
// Profile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Profile: Codable, JSONEncodable, Hashable {

    public var holders: Holders

    public init(holders: Holders) {
        self.holders = holders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case holders
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(holders, forKey: .holders)
    }
}

