//
// PushUriRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PushUriRequest: Codable, JSONEncodable, Hashable {

    public var uriDetails: UriDetails
    public var ns2: String?
    public var ver: String?
    public var ts: String?
    public var txn: String?
    public var orgId: String?
    public var keyHash: String?

    public init(uriDetails: UriDetails, ns2: String? = nil, ver: String? = nil, ts: String? = nil, txn: String? = nil, orgId: String? = nil, keyHash: String? = nil) {
        self.uriDetails = uriDetails
        self.ns2 = ns2
        self.ver = ver
        self.ts = ts
        self.txn = txn
        self.orgId = orgId
        self.keyHash = keyHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uriDetails
        case ns2
        case ver
        case ts
        case txn
        case orgId
        case keyHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uriDetails, forKey: .uriDetails)
        try container.encodeIfPresent(ns2, forKey: .ns2)
        try container.encodeIfPresent(ver, forKey: .ver)
        try container.encodeIfPresent(ts, forKey: .ts)
        try container.encodeIfPresent(txn, forKey: .txn)
        try container.encodeIfPresent(orgId, forKey: .orgId)
        try container.encodeIfPresent(keyHash, forKey: .keyHash)
    }
}

