//
// SipTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SipTransaction: Codable, JSONEncodable, Hashable {

    public var id: String
    public var amount: Double
    public var currencyCode: String
    public var txnType: SipTransactionType
    public var transactedAtUtc: Date

    public init(id: String, amount: Double, currencyCode: String, txnType: SipTransactionType, transactedAtUtc: Date) {
        self.id = id
        self.amount = amount
        self.currencyCode = currencyCode
        self.txnType = txnType
        self.transactedAtUtc = transactedAtUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case amount
        case currencyCode = "currency_code"
        case txnType = "txn_type"
        case transactedAtUtc = "transacted_at_utc"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(amount, forKey: .amount)
        try container.encode(currencyCode, forKey: .currencyCode)
        try container.encode(txnType, forKey: .txnType)
        try container.encode(transactedAtUtc, forKey: .transactedAtUtc)
    }
}

