//
// SipTransactionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SipTransactionType: String, Codable, CaseIterable {
    case buy = "Buy"
    case sell = "Sell"
    case others = "Others"
}
