//
// SupportedDocumentDetailsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SupportedDocumentDetailsDto: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var typeId: UUID
    public var logoUrl: String
    public var storageUrl: String
    public var issuedBy: String
    public var uploadedAtUtc: Date

    public init(id: UUID, typeId: UUID, logoUrl: String, storageUrl: String, issuedBy: String, uploadedAtUtc: Date) {
        self.id = id
        self.typeId = typeId
        self.logoUrl = logoUrl
        self.storageUrl = storageUrl
        self.issuedBy = issuedBy
        self.uploadedAtUtc = uploadedAtUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case typeId
        case logoUrl
        case storageUrl
        case issuedBy
        case uploadedAtUtc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(typeId, forKey: .typeId)
        try container.encode(logoUrl, forKey: .logoUrl)
        try container.encode(storageUrl, forKey: .storageUrl)
        try container.encode(issuedBy, forKey: .issuedBy)
        try container.encode(uploadedAtUtc, forKey: .uploadedAtUtc)
    }
}

