//
// SupportedEntityType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SupportedEntityType: String, Codable, CaseIterable {
    case individual = "Individual"
    case organization = "Organization"
    case both = "Both"
}
