//
// TermDepositInterestComputation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TermDepositInterestComputation: String, Codable, CaseIterable {
    case simple = "Simple"
    case compound = "Compound"
}
