//
// TermDepositBankInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TermDepositBankInformation: Codable, JSONEncodable, Hashable {

    public var bankName: String
    public var branch: String
    public var ifsc: String

    public init(bankName: String, branch: String, ifsc: String) {
        self.bankName = bankName
        self.branch = branch
        self.ifsc = ifsc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bankName = "bank_name"
        case branch
        case ifsc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bankName, forKey: .bankName)
        try container.encode(branch, forKey: .branch)
        try container.encode(ifsc, forKey: .ifsc)
    }
}

