//
// TermDepositTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TermDepositTransaction: Codable, JSONEncodable, Hashable {

    public var id: String
    public var amount: Double
    public var currencyCode: String
    public var narration: String
    public var txnType: TermDepositTransactionType
    public var mode: TermDepositTransactionMode
    public var transactedAtUtc: Date

    public init(id: String, amount: Double, currencyCode: String, narration: String, txnType: TermDepositTransactionType, mode: TermDepositTransactionMode, transactedAtUtc: Date) {
        self.id = id
        self.amount = amount
        self.currencyCode = currencyCode
        self.narration = narration
        self.txnType = txnType
        self.mode = mode
        self.transactedAtUtc = transactedAtUtc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case amount
        case currencyCode = "currency_code"
        case narration
        case txnType = "txn_type"
        case mode
        case transactedAtUtc = "transacted_at_utc"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(amount, forKey: .amount)
        try container.encode(currencyCode, forKey: .currencyCode)
        try container.encode(narration, forKey: .narration)
        try container.encode(txnType, forKey: .txnType)
        try container.encode(mode, forKey: .mode)
        try container.encode(transactedAtUtc, forKey: .transactedAtUtc)
    }
}

