//
// UpdateDataProcessingAgreement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update data processing agreement details. */
public struct UpdateDataProcessingAgreement: Codable, JSONEncodable, Hashable {

    /** Agreement version. */
    public var version: String
    /** Agreement body content. */
    public var body: String
    /** Agreement attachment file URL. */
    public var attachmentUrl: String

    public init(version: String, body: String, attachmentUrl: String) {
        self.version = version
        self.body = body
        self.attachmentUrl = attachmentUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case body
        case attachmentUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(body, forKey: .body)
        try container.encode(attachmentUrl, forKey: .attachmentUrl)
    }
}

