//
// UploadDocumentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** UploadDocumentResponse : Response of document upload. */
public struct UploadDocumentResponse: Codable, JSONEncodable, Hashable {

    /** Document issue request Id. */
    public var id: String
    /** Message. */
    public var message: String

    public init(id: String, message: String) {
        self.id = id
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(message, forKey: .message)
    }
}

