//
// UserDocumentDownload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserDocumentDownload: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var downloadUrl: String?
    public var expiresAtUtc: Date?
    public var ownerId: UUID?

    public init(id: UUID? = nil, downloadUrl: String? = nil, expiresAtUtc: Date? = nil, ownerId: UUID? = nil) {
        self.id = id
        self.downloadUrl = downloadUrl
        self.expiresAtUtc = expiresAtUtc
        self.ownerId = ownerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case downloadUrl
        case expiresAtUtc
        case ownerId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(downloadUrl, forKey: .downloadUrl)
        try container.encodeIfPresent(expiresAtUtc, forKey: .expiresAtUtc)
        try container.encodeIfPresent(ownerId, forKey: .ownerId)
    }
}

