{
  "openapi": "3.0.0",
  "info": {
    "title": "My Data My Consent - Developer API",
    "description": "Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.",
    "version": "1.0",
    "termsOfService": "https://mydatamyconsent.com/en-us/legal/terms-of-service",
    "contact": {
      "name": "Developer Support",
      "url": "https://mydatamyconsent.com/en-us/contact-us",
      "email": "support@mydatamyconsent.com"
    },
    "license": {
      "name": "EULA & Terms of Service",
      "url": "https://mydatamyconsent.com/en-us/legal/terms-of-service"
    }
  },
  "servers": [
    {
      "url": "https://api.mydatamyconsent.com",
      "description": "Production URL"
    }
  ],
  "tags": [
    {
      "name": "DataProcessingAgreements",
      "description": "Data Processing Agreements related operations."
    },
    {
      "name": "DataProvidersDiscovery",
      "description": "Data Providers Discovery Operations."
    },
    {
      "name": "Individuals",
      "description": "Individuals related operations."
    },
    {
      "name": "Organizations",
      "description": "Organizations related operations."
    },
    {
      "name": "SupportedIdentifiers",
      "description": "Supported Identifiers related operations."
    }
  ],
  "webhooks": {
    "consent_request_approved": {
      "summary": "sent when consent request is approved by the user / organization users."
    }
  },
  "paths": {
    "/v1/individuals/consent-templates": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get the paginated list of individual consent templates.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:ConsentRequestTemplates:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consent-templates/{template_id}": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get Individual consent template details by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:ConsentRequestTemplates:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consent-requests": {
      "post": {
        "tags": [
          "Individuals"
        ],
        "summary": "Create individual consent request.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:ConsentRequests:Request"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get all consent requests sent to Individuals.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:ConsentRequests:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consent-requests/{request_id}": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get Individual data consent request by id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:ConsentRequests:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consent-requests/{request_id}/cancel": {
      "put": {
        "tags": [
          "Individuals"
        ],
        "summary": "Cancel the Individual data request by id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:ConsentRequests:Cancel"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get the paginated list of Individual consents.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get Individuals consent details by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/documents": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get Individual consented document by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/documents/{document_id}": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get Individual consented document by document id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/documents/{document_id}/download": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Download Individual consented document by document id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/health/fhir/bundle": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get Individual consented Health Records by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/financial-accounts": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get all individual consented financial accounts.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/financial-accounts/{account_id}": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get individual consented financial account details.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/consents/{consent_id}/financial-accounts/{account_id}/transactions": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get individual consented financial account transactions.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/documents/types": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get paginated list of registered document types.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:DocumentTypes:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/documents/issued": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get paginated list of issued documents of given document type.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Documents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/documents/issued/{document_id}": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Get issued document.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Documents:Read"
            ]
          }
        ]
      }
    },
    "/v1/individuals/documents/issue": {
      "post": {
        "tags": [
          "Individuals"
        ],
        "summary": "Issue a new document to an individual user.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Documents:Issue"
            ]
          }
        ]
      }
    },
    "/v1/individuals/documents/issue/{issue_request_id}/upload": {
      "post": {
        "tags": [
          "Individuals"
        ],
        "summary": "Upload a document for issuance request of individual.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Individuals:Documents:Issue"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consent-templates": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get the paginated list of organization consent templates.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:ConsentRequestTemplates:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consent-templates/{template_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get Organization consent template details by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:ConsentRequestTemplates:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consent-requests": {
      "post": {
        "tags": [
          "Organizations"
        ],
        "summary": "Create consent request for an Organization.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:ConsentRequests:Request"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get all consent requests sent to Organizations.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:ConsentRequests:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consent-requests/{request_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get Organization data request by id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:ConsentRequests:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consent-requests/{request_id}/cancel": {
      "put": {
        "tags": [
          "Organizations"
        ],
        "summary": "Cancel the  Organization data request by id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:ConsentRequests:Cancel"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get the paginated list of Organization consents.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get Organization consent request details by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}/documents": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get Organization consent document by consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}/documents/{document_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get Organization consent document based on document id and consent id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}/documents/{document_id}/download": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Download Organization consent document by document id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}/financial-accounts": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get all organization consented financial accounts.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}/financial-accounts/{account_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get organization consented financial account details.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/consents/{consent_id}/financial-accounts/{account_id}/transactions": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get organization consented financial account transactions.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Consents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/documents/types": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get paginated list of registered document types.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:DocumentTypes:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/documents/issued": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get paginated list of issued documents of given document type.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Documents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/documents/issued/{document_id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Get issued document.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Documents:Read"
            ]
          }
        ]
      }
    },
    "/v1/organizations/documents/issue": {
      "post": {
        "tags": [
          "Organizations"
        ],
        "summary": "Issue a new document to an organization.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Documents:Issue"
            ]
          }
        ]
      }
    },
    "/v1/organizations/documents/issue/upload/{issue_request_id}": {
      "post": {
        "tags": [
          "Organizations"
        ],
        "summary": "Upload a document for issuance request of Organization.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "Organizations:Documents:Issue"
            ]
          }
        ]
      }
    },
    "/v1/data-agreements": {
      "get": {
        "tags": [
          "DataProcessingAgreements"
        ],
        "summary": "Get paginated data processing agreements.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "DataProcessingAgreements:Read"
            ]
          }
        ]
      }
    },
    "/v1/data-agreements/{id}": {
      "get": {
        "tags": [
          "DataProcessingAgreements"
        ],
        "summary": "Get data processing agreement by id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "DataProcessingAgreements:Read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "DataProcessingAgreements"
        ],
        "summary": "Delete a data processing agreement this will not delete a published or a agreement in use with consents.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "DataProcessingAgreements:Write"
            ]
          }
        ]
      }
    },
    "/v1/data-agreements/{id}/terminate": {
      "put": {
        "tags": [
          "DataProcessingAgreements"
        ],
        "summary": "Terminate a data processing agreement by id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "DataProcessingAgreements:Write"
            ]
          }
        ]
      }
    },
    "/v1/data-providers": {
      "get": {
        "tags": [
          "DataProvidersDiscovery"
        ],
        "summary": "Discover all data providers in my data my consent by country and filters.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "DataProviders:Read"
            ]
          }
        ]
      }
    },
    "/v1/data-providers/{id}": {
      "get": {
        "tags": [
          "DataProvidersDiscovery"
        ],
        "summary": "Get a data provider details by provider id.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "DataProviders:Read"
            ]
          }
        ]
      }
    },
    "/issuer/issuedoc/1/xml": {
      "post": {
        "tags": [
          "Individuals"
        ],
        "summary": "Digilocker compatible endpoint to issue document.",
        "security": [
          {
            "OAuth2ClientCredentials": []
          }
        ]
      }
    },
    "/v1/supported-identifiers/{country_iso2_code}": {
      "get": {
        "tags": [
          "SupportedIdentifiers"
        ],
        "summary": "Get all supported identifiers by country.",
        "security": [
          {
            "OAuth2ClientCredentials": [
              "SupportedIdentifiers:Read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2ClientCredentials": {
        "type": "oauth2",
        "description": "This API Uses OAuth2 Client Credentials Scheme.",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://accounts.mydatamyconsent.com/connect/token",
            "refreshUrl": "https://accounts.mydatamyconsent.com/connect/token",
            "scopes": {
              "SupportedIdentifiers:Read": "Read SupportedIdentifiers.",
              "DataProviders:Read": "Read DataProviders.",
              "DataProcessingAgreements:Read": "Read DataProcessingAgreements.",
              "DataProcessingAgreements:Write": "Read & Write DataProcessingAgreements.",
              "Individuals:DocumentTypes:Read": "Read Individual DocumentTypes.",
              "Individuals:Documents:Read": "Read Individual Issued Documents.",
              "Individuals:Documents:Issue": "Issue Individual Documents.",
              "Organizations:DocumentTypes:Read": "Read Organization DocumentTypes.",
              "Organizations:Documents:Read": "Read Organization Issued Documents.",
              "Organizations:Documents:Issue": "Issue Organization Documents.",
              "Individuals:ConsentRequests:Request": "Request Individual Consent requests.",
              "Individuals:ConsentRequests:Cancel": "Cancel Individual Consent requests.",
              "Individuals:ConsentRequests:Read": "Read Individual Consent requests.",
              "Organizations:ConsentRequests:Request": "Request Organization Consent requests.",
              "Organizations:ConsentRequests:Cancel": "Cancel Organization Consent requests.",
              "Organizations:ConsentRequests:Read": "Read Organization Consent requests.",
              "Individuals:Consents:Read": "Read Individual Consents.",
              "Organizations:Consents:Read": "Read Organization Consents.",
              "Individuals:ConsentRequestTemplates:Read": "Read Individual Consent Request templates.",
              "Organizations:ConsentRequestTemplates:Read": "Read Organization Consent Request templates."
            }
          }
        }
      }
    }
  }
}