name: MyDataMyConsent
targets:
  MyDataMyConsent:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [MyDataMyConsent]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
