//
// DataConsentRequesterDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataConsentRequesterDto: Codable, Hashable {

    public var name: String?
    public var logoUrl: String?
    public var description: String?
    public var website: String?
    public var supportEmail: String?
    public var helpLineNumber: String?

    public init(name: String? = nil, logoUrl: String? = nil, description: String? = nil, website: String? = nil, supportEmail: String? = nil, helpLineNumber: String? = nil) {
        self.name = name
        self.logoUrl = logoUrl
        self.description = description
        self.website = website
        self.supportEmail = supportEmail
        self.helpLineNumber = helpLineNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case logoUrl
        case description
        case website
        case supportEmail
        case helpLineNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(website, forKey: .website)
        try container.encodeIfPresent(supportEmail, forKey: .supportEmail)
        try container.encodeIfPresent(helpLineNumber, forKey: .helpLineNumber)
    }
}

