//
// FilterType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FilterType: String, Codable, CaseIterable {
    case transactionType = "TransactionType"
    case transactionAmount = "TransactionAmount"
    case transactionDescription = "TransactionDescription"
}
