//
// IdentityClaim.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IdentityClaim: String, Codable, CaseIterable {
    case email = "Email"
    case firstName = "FirstName"
    case lastName = "LastName"
}
