//
// Operator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Operator: String, Codable, CaseIterable {
    case equalTo = "EqualTo"
    case notEqualto = "NotEqualto"
    case textContains = "TextContains"
    case greaterThan = "GreaterThan"
    case lessThan = "LessThan"
    case greaterThanOrEqualTo = "GreaterThanOrEqualTo"
    case lessThanOrEqualTo = "LessThanOrEqualTo"
}
