//
// PushUriResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PushUriResponse: Codable, Hashable {

    public var responseStatus: String?
    public var responseMessage: String?
    public var ns2: String?
    public var ver: String?
    public var ts: String?
    public var txn: String?
    public var orgId: String?

    public init(responseStatus: String? = nil, responseMessage: String? = nil, ns2: String? = nil, ver: String? = nil, ts: String? = nil, txn: String? = nil, orgId: String? = nil) {
        self.responseStatus = responseStatus
        self.responseMessage = responseMessage
        self.ns2 = ns2
        self.ver = ver
        self.ts = ts
        self.txn = txn
        self.orgId = orgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case responseStatus
        case responseMessage
        case ns2
        case ver
        case ts
        case txn
        case orgId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(responseStatus, forKey: .responseStatus)
        try container.encodeIfPresent(responseMessage, forKey: .responseMessage)
        try container.encodeIfPresent(ns2, forKey: .ns2)
        try container.encodeIfPresent(ver, forKey: .ver)
        try container.encodeIfPresent(ts, forKey: .ts)
        try container.encodeIfPresent(txn, forKey: .txn)
        try container.encodeIfPresent(orgId, forKey: .orgId)
    }
}

