//
// SupportedIdentifiersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SupportedIdentifiersAPI {

    /**
     Get all supported identifiers by country.
     
     - parameter countryIso2Code: (path) Country ISO 2 code. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAllSupportedIdentifiers(countryIso2Code: String, apiResponseQueue: DispatchQueue = MyDataMyConsentAPI.apiResponseQueue, completion: @escaping ((_ data: SupportedIdentifiersByCountry?, _ error: Error?) -> Void)) -> RequestTask {
        return getAllSupportedIdentifiersWithRequestBuilder(countryIso2Code: countryIso2Code).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all supported identifiers by country.
     - GET /v1/supported-identifiers/{countryIso2Code}
     - parameter countryIso2Code: (path) Country ISO 2 code. 
     - returns: RequestBuilder<SupportedIdentifiersByCountry> 
     */
    open class func getAllSupportedIdentifiersWithRequestBuilder(countryIso2Code: String) -> RequestBuilder<SupportedIdentifiersByCountry> {
        var localVariablePath = "/v1/supported-identifiers/{countryIso2Code}"
        let countryIso2CodePreEscape = "\(APIHelper.mapValueToPathItem(countryIso2Code))"
        let countryIso2CodePostEscape = countryIso2CodePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{countryIso2Code}", with: countryIso2CodePostEscape, options: .literal, range: nil)
        let localVariableURLString = MyDataMyConsentAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SupportedIdentifiersByCountry>.Type = MyDataMyConsentAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
